/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-11 06:09:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import wishbook.model.vo.WishBook;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class adminIndexView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../inc/adminTemplate.jsp", Long.valueOf(1570722332602L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("wishbook.model.vo.WishBook");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 시맨틱 UI -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css\"/>\r\n");
      out.write(" \t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  \t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js\"></script>\r\n");
      out.write(" <!-- Custom CSS -->\r\n");
      out.write("\t<link rel = \"stylesheet\" type=\"text/css\" href=\"/sori/resources/css/Admin.css\">\r\n");
      out.write("\t  <script src=\"/sori/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- 폰트변경 -->\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t@font-face { font-family: 'S-CoreDream-7ExtraBold'; \r\n");
      out.write("\t\t\t\t\t src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-7ExtraBold.woff') format('woff'); \r\n");
      out.write("\t\t\t\t\t font-weight: normal; \r\n");
      out.write("\t\t\t\t\t font-style: normal; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t* { font-family: 'S-CoreDream-7ExtraBold';}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 상단 바 시작! -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div class=\"topbar\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t<span class=\"topname\"><a href=\"/sori/index.jsp\" target=\"_blank\"><i class=\"home icon\"></i></a>SORIJIEUM <span style=\"color:#4ecdc4\">ADMIN</span></span>\r\n");
      out.write("\t\t\t<div id=\"adminname\"><a href=\"\">최민영</a> 님!&nbsp;&nbsp;&nbsp;<button class=\"ui mini teal button\">Logout</button></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("<!-- 상단 바 끝! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 사이드 메뉴 바 시작!-->\r\n");
      out.write("<aside>\r\n");
      out.write("<div class=\"menubar\" style=\"overflow:hidden;\">\r\n");
      out.write("<nav>\r\n");
      out.write("\t<ul class=\"vertical-menu\">\r\n");
      out.write("\t\t<li style=\"font-weight: 600; font-size:12pt\"><a href=\"/sori/views/admin/adminIndexView.jsp\"><i class=\"home icon\"></i>MAIN</a></li>\r\n");
      out.write("\t\t<li style=\"font-weight: 600; font-size:12pt\"><a href=\"javascript:;\"><i class=\"book icon\"></i>도서</a></li>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/blist.ad\">　도서목록</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminAddBookForm.jsp\">　도서추가</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminWishBookListView.jsp\">　도서신청내역</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t<li style=\"font-weight: 600; font-size:12pt\"><a href=\"\"><i class=\"user icon\"></i>사용자</a></li>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminUserListView.jsp\">　회원정보조회</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminQuitUserView.jsp\">　회원탈퇴관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminListView.jsp\">　권한관리</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t<li style=\"font-weight: 600; font-size:12pt\"><a href=\"\"><i class=\"clipboard list icon\"></i>게시판</a></li>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"/sori/views/admin/adminQnaListView.jsp\">　문의글관리</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</aside>\r\n");
      out.write("<!-- 사이드 메뉴 끝! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <footer class=\"site-footer\" style=\"overflow:hidden;\">\r\n");
      out.write("        <p>\r\n");
      out.write("          &copy; Copyrightⓒ 2019 <strong>sorijieum @minyoung.</strong> All Rights Reserved.<br>\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Date sysdate = new Date();
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일");
	ArrayList<WishBook> wbWaitList = (ArrayList<WishBook>)request.getAttribute("wbWaitList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>소리지음 관리자 시스템</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Content 시작! -->\r\n");
      out.write("<section class=\"contentsection\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--오늘의 차트 시작-->\r\n");
      out.write("            <div class=\"base\">\r\n");
      out.write("\t            <i class=\"large blue check circle icon\"></i>\r\n");
      out.write("\t            <span class=\"sysdate\">");
      out.print( sdf.format(sysdate) );
      out.write("</span>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <div class=\"data\">\r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- 도서 섹션-->          \r\n");
      out.write("\t            <div class=\"data-box\">\r\n");
      out.write("\t            \t<div class=\"data-section1\">\r\n");
      out.write("\t            \t\t<i class=\"huge yellow book icon\"></i>\r\n");
      out.write("\t            \t\t<div class=\"data-title\" style=\"color: #f2c61f\">도서</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section2\">\r\n");
      out.write("\t            \t\t<div>신청도서</div>\r\n");
      out.write("\t            \t\t<div>제작중도서</div>\r\n");
      out.write("\t            \t\t<div>완료도서</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section3\">\r\n");
      out.write("\t            \t\t<div><span class=\"todaybook\"><a href=\"\">");
      out.print( wbWaitList );
      out.write("</span></a> 권</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todaybook\"><a href=\"\">8</span></a> 권</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todaybook\"><a href=\"\">333</span></a> 권</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- 게시글 섹션-->\r\n");
      out.write("\t            <div class=\"data-box\">\r\n");
      out.write("\t            \t<div class=\"data-section1\">\r\n");
      out.write("\t            \t\t<i class=\"huge red clipboard list icon\"></i>\r\n");
      out.write("\t            \t\t<div class=\"data-title\" style=\"color: #d95c5c\">게시글</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section2\">\r\n");
      out.write("\t            \t\t<div>새 문의글</div>\r\n");
      out.write("\t            \t\t<div>미답변 문의</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section3\">\r\n");
      out.write("\t            \t\t<div><span class=\"todayboard\"><a href=\"\">10</span></a> 건</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todayboard\"><a href=\"\">6</span></a> 건</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- 이용자 섹션-->\r\n");
      out.write("\t            <div class=\"data-box\">\r\n");
      out.write("\t            \t<div class=\"data-section1\">\r\n");
      out.write("\t            \t\t<i class=\"huge green user icon\"></i>\r\n");
      out.write("\t            \t\t<div class=\"data-title\" style=\"color: #5bbd72\">이용자</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section2\">\r\n");
      out.write("\t            \t\t<div>신규회원</div>\r\n");
      out.write("\t            \t\t<div>탈퇴회원</div>\r\n");
      out.write("\t            \t\t<div>TOTAL</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section3\">\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser1\"><a href=\"\">2</span></a> 명</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser1\"><a href=\"\">0</span></a> 명</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser1\"><a href=\"\">43</span></a> 명</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<!-- 제작자 섹션-->\r\n");
      out.write("\t            <div class=\"data-box\">\r\n");
      out.write("\t            \t<div class=\"data-section1\">\r\n");
      out.write("\t            \t\t<i class=\"huge blue user icon\"></i>\r\n");
      out.write("\t            \t\t<div class=\"data-title\" style=\"color: #3b83c0\">제작자</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section2\">\r\n");
      out.write("\t            \t\t<div>신규회원</div>\r\n");
      out.write("\t            \t\t<div>탈퇴회원</div>\r\n");
      out.write("\t            \t\t<div>TOTAL</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            \t<div class=\"data-section3\">\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser2\"><a href=\"\">50</span></a> 명</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser2\"><a href=\"\">4</span></a> 명</div>\r\n");
      out.write("\t            \t\t<div><span class=\"todayuser2\"><a href=\"\">254</span></a> 명</div>\r\n");
      out.write("\t            \t</div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            \t            \r\n");
      out.write("\t            </div>\t            \r\n");
      out.write("            </div>\r\n");
      out.write("       <!-- 오늘의 차트 끝! -->\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("</section>\r\n");
      out.write("<!-- Content 끝! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
