/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-11 08:07:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberLoginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/inc/top.jsp", Long.valueOf(1570683274715L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인화면</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css\"/>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sori/resources/css/member.css\">\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write(" <!-- favicon 위치 -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"/sori/resources/images/favicon.ico\">\n");
      out.write("<link rel=\"icon\" href=\"/sori/resources/images/favicon.ico\">\n");
      out.write("<!-- 시맨틱유아이 cdn -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css\"/>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js\"></script>\n");
      out.write("  <!-- bootstrap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" \n");
      out.write("integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sori/resources/css/bookmaking.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"/sori/resources/js/jquery-3.4.1.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("@font-face { font-family: 'S-CoreDream-7ExtraBold'; \n");
      out.write("\t\t\t src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-7ExtraBold.woff') format('woff'); \n");
      out.write("\t\t\t font-weight: normal; \n");
      out.write("\t\t\t font-style: normal; }\n");
      out.write("\n");
      out.write("* { font-family: 'S-CoreDream-7ExtraBold';}\n");
      out.write("\t\t\t \n");
      out.write(" ul{width:650px;height:20px;list-style:none;padding-left:150px;} /*position fixed는 스크롤이 내려가도 상단고정  */\n");
      out.write("ul li{float:left;/* margin-right:8px; *//* padding-left:30px; */}\n");
      out.write("ul li a{font-size:20px;color:black;font-weight:bold;text-decoration:none}\n");
      out.write("ul li a:hover{background:#ccc;color#fff;}\n");
      out.write("\n");
      out.write("footer{\n");
      out.write("     position:fixed;\n");
      out.write("     left:0;\n");
      out.write("     bottom : 0;\n");
      out.write("     width: 100%;\n");
      out.write("     height: 50px;\n");
      out.write("     background-color: #fbbe09;\n");
      out.write("     overflow:hidden;\"\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<div class=\"ui top fixed menu\" style=\"height:100px;overflow:hidden;\">\n");
      out.write("  <div class=\"item\">\n");
      out.write("\t<a href=\"/sori/index.jsp\"><img src=\"/sori/resources/images/logo.png\" width=\"100px\" height=\"100px\" align=\"left\"></a>\n");
      out.write("  </div>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/sorijieumIntro.jsp\">사이트 소개</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/booksearch/bookSearchList.jsp\">도서 검색</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/bookmaking/bmmain.jsp\">도서 제작</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardwishbook/wishbookListView.jsp\">도서 신청</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardnotice/noticeListView.jsp\">공지사항</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardfaq/faqListView.jsp\">FAQ</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardqna/qnaListView.jsp\">Q&A</a>\n");
      out.write("</div>\n");
      out.write("<br><br><br>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<footer style=\"text-align: center;\">\n");
      out.write("\t\t<p style=\"margin-top:1%;\">\n");
      out.write("          &copy; Copyrights <strong>sorijieum</strong>.\n");
      out.write("          All Rights Reserved Created with sorijieum\n");
      out.write("        </p>\n");
      out.write("</footer>\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section class=\"my-section\">\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<form>\r\n");
      out.write("\r\n");
      out.write("<div class=\"ui form\" style=\"margin-top:10px;\">\r\n");
      out.write("  <div class=\"inline field\">\r\n");
      out.write("    <label>아 이 디</label>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"text\" placeholder=\"아이디\" style=\"width:300px;height:50px;\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"inline field\">\r\n");
      out.write("    <label>비밀번호</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"password\" placeholder=\"비밀번호\" style=\"width:300px;height:50px;\">\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"autoLogin\" checked>&nbsp;자동로그인\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"/sori/views/member/memberSearchIdPwd.jsp\">아이디|비밀번호 찾기</a>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<input type=\"submit\" value=\"로그인\" class=\"ui yellow button\" style=\"color:black;width:200px;height:50px;font-size:20pt;\">\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
