/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-11 08:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.boardwishbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wishbookListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../inc/top.jsp", Long.valueOf(1570683274715L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write(" <!-- favicon 위치 -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"/sori/resources/images/favicon.ico\">\n");
      out.write("<link rel=\"icon\" href=\"/sori/resources/images/favicon.ico\">\n");
      out.write("<!-- 시맨틱유아이 cdn -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css\"/>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js\"></script>\n");
      out.write("  <!-- bootstrap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" \n");
      out.write("integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sori/resources/css/bookmaking.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"/sori/resources/js/jquery-3.4.1.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("@font-face { font-family: 'S-CoreDream-7ExtraBold'; \n");
      out.write("\t\t\t src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-7ExtraBold.woff') format('woff'); \n");
      out.write("\t\t\t font-weight: normal; \n");
      out.write("\t\t\t font-style: normal; }\n");
      out.write("\n");
      out.write("* { font-family: 'S-CoreDream-7ExtraBold';}\n");
      out.write("\t\t\t \n");
      out.write(" ul{width:650px;height:20px;list-style:none;padding-left:150px;} /*position fixed는 스크롤이 내려가도 상단고정  */\n");
      out.write("ul li{float:left;/* margin-right:8px; *//* padding-left:30px; */}\n");
      out.write("ul li a{font-size:20px;color:black;font-weight:bold;text-decoration:none}\n");
      out.write("ul li a:hover{background:#ccc;color#fff;}\n");
      out.write("\n");
      out.write("footer{\n");
      out.write("     position:fixed;\n");
      out.write("     left:0;\n");
      out.write("     bottom : 0;\n");
      out.write("     width: 100%;\n");
      out.write("     height: 50px;\n");
      out.write("     background-color: #fbbe09;\n");
      out.write("     overflow:hidden;\"\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<div class=\"ui top fixed menu\" style=\"height:100px;overflow:hidden;\">\n");
      out.write("  <div class=\"item\">\n");
      out.write("\t<a href=\"/sori/index.jsp\"><img src=\"/sori/resources/images/logo.png\" width=\"100px\" height=\"100px\" align=\"left\"></a>\n");
      out.write("  </div>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/sorijieumIntro.jsp\">사이트 소개</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/booksearch/bookSearchList.jsp\">도서 검색</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/bookmaking/bmmain.jsp\">도서 제작</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardwishbook/wishbookListView.jsp\">도서 신청</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardnotice/noticeListView.jsp\">공지사항</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardfaq/faqListView.jsp\">FAQ</a>\n");
      out.write("  <a class=\"item\" href=\"/sori/views/boardqna/qnaListView.jsp\">Q&A</a>\n");
      out.write("</div>\n");
      out.write("<br><br><br>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<footer style=\"text-align: center;\">\n");
      out.write("\t\t<p style=\"margin-top:1%;\">\n");
      out.write("          &copy; Copyrights <strong>sorijieum</strong>.\n");
      out.write("          All Rights Reserved Created with sorijieum\n");
      out.write("        </p>\n");
      out.write("</footer>\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>도서신청</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/first/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\tshowDiv();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"input[name=item]\").on(\"change\", function(){\r\n");
      out.write("\t\t\tshowDiv();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showDiv(){\r\n");
      out.write("\t\tif($(\"input[name=item]\").eq(0).is(\":checked\")){\r\n");
      out.write("\t\t\t$(\"#titlediv\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#authordiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"input[name=item]\").eq(1).is(\":checked\")){\r\n");
      out.write("\t\t\t$(\"#titlediv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#authordiv\").css(\"display\", \"block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Semantic UI CND -->\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css\"/>\r\n");
      out.write(" \t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write(" \t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js\"></script>\r\n");
      out.write("  <!-- CUSTOM CSS -->\r\n");
      out.write("<link rel = \"stylesheet\" type=\"text/css\" href=\"/sori/resources/css/board.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Content 시작! -->\r\n");
      out.write("\t<section class=\"my-section\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--도서신청 시작-->\r\n");
      out.write("\t<div class=\"my-content\">\r\n");
      out.write("\t<a class=\"massive ui yellow label\" style=\"font-size: 30px\">도서신청</a>\r\n");
      out.write("\t<span style=\"color:#fbbe09; font-weight:600\">│</span>\r\n");
      out.write("\t<span style=\"color:grey\">도서신청 게시판입니다</span>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t<!-- 도서신청 목록 시작 -->\r\n");
      out.write("\t\t<table class=\"my-listTable\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"5%\">No</th>\r\n");
      out.write("\t\t\t\t<th width=\"45%\">도서명</th>\r\n");
      out.write("\t\t\t\t<th width=\"15%\">저자명</th>\r\n");
      out.write("\t\t\t\t<th width=\"15%\">신청자ID</th>\r\n");
      out.write("\t\t\t\t<th width=\"10%\">신청일</th>\r\n");
      out.write("\t\t\t\t<th width=\"10%\">진행사항</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align:left;\"><a href=\"/sori/views/boardwishbook/wishbookDetailView.jsp\">아몬드</a></td>\r\n");
      out.write("\t\t\t\t<td>손원평</td>\r\n");
      out.write("\t\t\t\t<td>user003</td>\r\n");
      out.write("\t\t\t\t<td>2019/01/12</td>\r\n");
      out.write("\t\t\t\t<td>승인</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t<!--도서신청 목록 끝-->\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div align=\"right\"><a class=\"big ui black label\" href=\"\">나의신청내역</a>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;<a class=\"big ui black label\" href=\"/sori/views/boardwishbook/wishbookAddForm.jsp\">글쓰기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 페이징 시작 -->\r\n");
      out.write("\t\t<div align=\"center\">페이징 버튼 부분(추후 코딩 예정)</div>\r\n");
      out.write("\t<!-- 페이징 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<br><hr><br>\r\n");
      out.write("\t<!-- 검색창 시작 -->\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"item\" value=\"title\" checked> 도서명 &nbsp; &nbsp; &nbsp; \r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"item\" value=\"author\"> 저자명&nbsp; &nbsp; &nbsp; \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"titlediv\">\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"search\" value=\"title\">\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t<input type=\"search\" name=\"keyword\"></label>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"authordiv\">\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"search\" value=\"author\">\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t<input type=\"search\" name=\"keyword\"></label>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t<!-- 검색창 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--도서신청 끝-->\r\n");
      out.write("\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Content 끝! -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
